### ISSUE TITLE
Nepali ligatures not working

### ISSUE THREAD

**Issue by nirodhvana** [arakiken/mlterm#131]
Nepali ligatures dont work properly even though they also use devnagari like hindi

the spacing is sometimes trash and 
ि
 ी
 dont work

is there an option i need to compile it with?
 I can provide more info if you need.

**Comment by nirodhvana** [comment]
I seem dumb rn dont I :)

**Comment by arakiken** [comment]
Will you show me ~/.mlterm/main, ~/.mlterm/msg.log and what 'mlterm --version' outputs?
What happens if you start mlterm with -otl option?

**Comment by nirodhvana** [comment]
the version output is 3.9.0
no .mlterm/main and heres my r/unixporn with -otl option on left and the .mlterm/msg.log on the right

![Image](https://github.com/user-attachments/assets/9abac917-ec19-4c4d-8f2d-e8023e388770)

:)

**Comment by nirodhvana** [comment]
@arakiken think this has something to do with puttig the write options while compiling.

**Comment by nirodhvana** [comment]
@arakiken ive tried everything in the guide : https://github.com/arakiken/mlterm/blob/master/doc/en/README.indic

still cant get it to work. Nepali uses the same devanagari script that hindi uses, so it should work but it doesnt :(

**Comment by nirodhvana** [comment]
@arakiken is there some inherent difference between nepali and hindi even though they use the same script?

**Comment by arakiken** [comment]
Hmm... I think there is no difference between nepali and hindi in setting mlterm.
Building mlterm with harfbuzz and start it with --otl option shows a following screen in my environment.
![Image](https://github.com/user-attachments/assets/5c94ba39-8705-4bff-9eed-2f3fa7eeeb26)

1) Have you already tried mlterm 3.9.3 or git head?

2) Does ./configure output a following line in buiding mlterm?
OpenType Layout                   : yes (harfbuzz)

3) Which font do you use to show devanagari?

**Comment by nirodhvana** [comment]
> Hmm... I think there is no difference between nepali and hindi in setting mlterm. Building mlterm with harfbuzz and start it with --otl option shows a following screen in my environment. ![Image](https://github.com/user-attachments/assets/5c94ba39-8705-4bff-9eed-2f3fa7eeeb26)
> 
> 1. Have you already tried mlterm 3.9.3 or git head?
> 2. Does ./configure output a following line in buiding mlterm?
>    OpenType Layout                   : yes (harfbuzz)
> 3. Which font do you use to show devanagari?

1. I did compile 3.9.3

2. Yes it does show:

![Image](https://github.com/user-attachments/assets/b7834dd6-070f-4e28-bbb4-df57bed663f1)

3. It definetely seems to be the fonts causing the problem. I couldn't setup my fonts(https://github.com/nirodhvana/reservoir/blob/master/.local/share/fonts/nepali-fonts/fonts/nepali.ttf) because i couldnt understand the documentation :(

**Comment by arakiken** [comment]
nepali.ttf doesn't have any open type layout table for devanagari.
mlterm depends on open type layout tables in otf fonts to render complex text layout languages such as devanagari.

ex.) NotoSansDevanagari
$ fc-query NotoSansDevanagari-Medium.ttf
...
capability: "otlayout:DFLT otlayout:dev2 otlayout:deva"(s)

Sorry but it is impossible for mlterm to show devanagari correctly with the use of nepali.ttf for now.

**Comment by nirodhvana** [comment]
> nepali.ttf doesn't have any open type layout table for devanagari. mlterm depends on open type layout tables in otf fonts to render complex text layout languages such as devanagari.
> 
> ex.) NotoSansDevanagari $ fc-query NotoSansDevanagari-Medium.ttf ... capability: "otlayout:DFLT otlayout:dev2 otlayout:deva"(s)
> 
> Sorry but it is impossible for mlterm to show devanagari correctly with the use of nepali.ttf for now.

@arakiken is there anyway to add an opentype layout table for devnagari in the font ? Otherwise i can be down with the noto sans devnagari too. Dont think it's in the ubuntu repos tho.

**Comment by nirodhvana** [comment]
@arakiken 
Will this work too? Found it in void's repos.

**Comment by arakiken** [comment]
I found a bug where glyphs were not drawn in the correct position with some fonts, such as annapurna you suggested.
I fixed this bug. -> https://github.com/arakiken/mlterm/commit/f2c5024e3b215cb2b4e5f9a85d55e211e8451c30
If you use annapurna font, please rebuild mlterm.
After this fix, mlterm shows devanagari as attached by following steps.

1) Add "U+900-97f = Annapurna SIL" to ~/.mlterm/aafont.
2) Start mlterm with --otl option.

![Image](https://github.com/user-attachments/assets/77bd7627-3ce2-489f-bb91-ff519f826550)

**Comment by nirodhvana** [comment]
> I found a bug where glyphs were not drawn in the correct position with some fonts, such as annapurna you suggested. I fixed this bug. -> [f2c5024](https://github.com/arakiken/mlterm/commit/f2c5024e3b215cb2b4e5f9a85d55e211e8451c30) If you use annapurna font, please rebuild mlterm. After this fix, mlterm shows devanagari as attached by following steps.
> 
> 1. Add "U+900-97f = Annapurna SIL" to ~/.mlterm/aafont.
> 2. Start mlterm with --otl option.
> 
> ![Image](https://github.com/user-attachments/assets/77bd7627-3ce2-489f-bb91-ff519f826550)

Thank you for the work. I still cant seem to figure out how to setup fonts right. Do you have a guide for that? I wanna RTFM LOL

**Comment by nirodhvana** [comment]
> I found a bug where glyphs were not drawn in the correct position with some fonts, such as annapurna you suggested. I fixed this bug. -> [f2c5024](https://github.com/arakiken/mlterm/commit/f2c5024e3b215cb2b4e5f9a85d55e211e8451c30) If you use annapurna font, please rebuild mlterm. After this fix, mlterm shows devanagari as attached by following steps.
> 
> 1. Add "U+900-97f = Annapurna SIL" to ~/.mlterm/aafont.
> 2. Start mlterm with --otl option.
> 
> ![Image](https://github.com/user-attachments/assets/77bd7627-3ce2-489f-bb91-ff519f826550)

I have this wierd issue with https://github.com/hchargois/gohufont
where you can see that the characters sometimes mashed up: 

![Image](https://github.com/user-attachments/assets/2e995f2e-669e-492e-82fb-8629a5e46aab)

**Comment by nirodhvana** [comment]
@arakiken 
seems the commit fixed it thank you
also :)
does mlterm have this feature? think it might come in handy. https://github.com/kovidgoyal/kitty/issues/461

**Comment by arakiken** [comment]
> I have this wierd issue with https://github.com/hchargois/gohufont where you can see that the characters sometimes mashed up:
> 
> [@arakiken](https://github.com/arakiken) ill see if that commit fixes it thanks.

If you use proportional fonts, try to use -V option.

**Comment by arakiken** [comment]
> [@arakiken](https://github.com/arakiken) seems the commit fixed it thank you also :) does mlterm have this feature? think it might come in handy. [kovidgoyal/kitty#461](https://github.com/kovidgoyal/kitty/issues/461)

Supporting this feature would require a major overhaul.
I'll consider it for the future.

**Comment by nirodhvana** [comment]
> > I have this wierd issue with https://github.com/hchargois/gohufont where you can see that the characters sometimes mashed up:
> > [@arakiken](https://github.com/arakiken) ill see if that commit fixes it thanks.
> 
> If you use proportional fonts, try to use -V option.

I dont know much about fonts. This is the one i'm using https://font.gohu.org do i need that option for it ?

**Comment by nirodhvana** [comment]
> > [@arakiken](https://github.com/arakiken) seems the commit fixed it thank you also :) does mlterm have this feature? think it might come in handy. [kovidgoyal/kitty#461](https://github.com/kovidgoyal/kitty/issues/461)
> 
> Supporting this feature would require a major overhaul. I'll consider it for the future.

It would be easier for editing scripts with lots of ligatures etc like devanagari

**Comment by arakiken** [comment]
> > > I have this wierd issue with https://github.com/hchargois/gohufont where you can see that the characters sometimes mashed up:
> > > [@arakiken](https://github.com/arakiken) ill see if that commit fixes it thanks.
> > 
> > 
> > If you use proportional fonts, try to use -V option.
> 
> I dont know much about fonts. This is the one i'm using https://font.gohu.org do i need that option for it ?

If mlterm correctly loads gohu font which is monospace, -V option is not necessary.
I think that the font shown in the screenshot you uploaded is not gohu font but some kind of a proportional font which has ligature open type layout table.
While mlterm draws glyphs in a propotional font forcibly as monospace, mlterm with -V option draws them natually, so I think that -V option improves a little.
But the essential reason why some glyphs are mixed is because mlterm with --otl option processes text with the ligature table in the font.
Anyway, if mlterm could load gohu font correctly, this would solve the problem.

**Comment by nirodhvana** [comment]
> > > > I have this wierd issue with https://github.com/hchargois/gohufont where you can see that the characters sometimes mashed up:
> > > > [@arakiken](https://github.com/arakiken) ill see if that commit fixes it thanks.
> > > 
> > > 
> > > If you use proportional fonts, try to use -V option.
> > 
> > 
> > I dont know much about fonts. This is the one i'm using https://font.gohu.org do i need that option for it ?
> 
> If mlterm correctly loads gohu font which is monospace, -V option is not necessary. I think that the font shown in the screenshot you uploaded is not gohu font but some kind of a proportional font which has ligature open type layout table. While mlterm draws glyphs in a propotional font forcibly as monospace, mlterm with -V option draws them natually, so I think that -V option improves a little. But the essential reason why some glyphs are mixed is because mlterm with --otl option processes text with the ligature table in the font. Anyway, if mlterm could load gohu font correctly, this would solve the problem.

Mlterm does display gohu correctly and the font in the picture wasn't actually gohu and i found out latet that my config was messed up

**Comment by nirodhvana** [comment]
@arakiken weird characters showup while using cat and editing nepali
and ligatures also cutoff at weird parts

my config:https://github.com/nirodhvana/reservoir/tree/master/.mlterm

cat

![Image](https://github.com/user-attachments/assets/0ef10a7b-5f65-4e4d-8a50-d00b6c159bd6)

neovim

![Image](https://github.com/user-attachments/assets/76347a7c-c21f-403e-9980-d1de90f8fdb9)

**Comment by nirodhvana** [comment]
> Hmm... I think there is no difference between nepali and hindi in setting mlterm. Building mlterm with harfbuzz and start it with --otl option shows a following screen in my environment. ![Image](https://github.com/user-attachments/assets/5c94ba39-8705-4bff-9eed-2f3fa7eeeb26)
> 
> 1. Have you already tried mlterm 3.9.3 or git head?
> 2. Does ./configure output a following line in buiding mlterm?
>    OpenType Layout                   : yes (harfbuzz)
> 3. Which font do you use to show devanagari?

@arakiken Can you share your config? I cant get the font to look like the one in the picture at all
